modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License v3.0"

[[mods]]
modId="spintymod"
version="1.3.11"
displayName="DeptaniaOptions"
authors="Spinty"
description='''Spinty's awesome mod.'''

[[dependencies.spintymod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.spintymod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
